spring:
  application:
    name: Passbook
  datasource:
    url: jdbc:mysql://localhost:3306/passbook?autoReconnect=true
    username: root
    password:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: passbook
    listener:
      concurrency: 4
  data:
    hbase:
      quorum: 128.0.0.1:2181
      rootDir: file:///Users/mypath..
      nodeParent: /hbase
  redis:
    host: 127.0.0.1
    port: 6379

server:
  port:9528

logging:
  file: passbook.log
  level: debug
